# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=dev
  - php bin/console doctrine:schema:create --env=dev

# Run script
script:
  #- phpunit
  - php bin/console server:start
  #- phpcs
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git
  - php PHP_CodeSniffer/bin/phpcs -h
  - php PHP_CodeSniffer/bin/phpcbf -h
  #- security check
  #- php bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

# After a build, send email notification with the build results
notifications:
  email:
    recipients:
      - fx.brazier@gmail.com
    on_success: never
    on_failure: always

# Deploy on Heroku
deploy:
  provider: heroku
  app: myfcapi-dev
  api_key:
    secure: "1c460653-ea7c-400c-adc7-bdcbe59f997f"

  
