<?php

namespace AppBundle\Repository;

/**
 * ClubStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubStatRepository extends \Doctrine\ORM\EntityRepository
{
}
