<?php

namespace AppBundle\Repository;

/**
 * JerseyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JerseyRepository extends \Doctrine\ORM\EntityRepository
{
}
