<?php

namespace AppBundle\Repository;

/**
 * JerseyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JerseyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
