<?php

namespace AppBundle\Repository;

/**
 * LeagueResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueResultRepository extends \Doctrine\ORM\EntityRepository
{
}
