<?php

namespace AppBundle\Repository;

/**
 * PlayerPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
