<?php

namespace AppBundle\Repository;

/**
 * PlayerPositionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerPositionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
