<?php

namespace AppBundle\Repository;

/**
 * PlayerStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatRepository extends \Doctrine\ORM\EntityRepository
{
}
